import os, sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
"""Emits src/client/Kits/AntiMagic/Animations.luau from asta_anims.py."""
from asta_anims import *

SINE_IO = ('Sine', 'InOut'); QUAD_IN = ('Quad', 'In'); QUART_OUT = ('Quart', 'Out')
SINE_OUT = ('Sine', 'Out'); LINEAR = ('Linear', 'Out'); QUAD_OUT = ('Quad', 'Out')

SWING_EASE = [None, SINE_IO, QUAD_IN, QUART_OUT, SINE_OUT]
OVERLAP = {'Head': -0.01, 'RightArm': 0.012, 'LeftArm': 0.02, 'Sword': 0.03}

SPEC = {
    'Idle': dict(keys=IDLE, ease=[None, SINE_IO, SINE_IO], loop=True,
                 delays={'Head': 0.12, 'RightArm': 0.08, 'Sword': 0.16, 'LeftArm': 0.2},
                 doc="Standing still: wide stance, sword resting on the right shoulder, slow breathing."),
    'Run': dict(keys=RUN, ease=[None, SINE_IO, SINE_IO, SINE_IO, SINE_IO], loop=True,
                delays={'Head': 0.04, 'Sword': 0.05, 'LeftArm': 0.02},
                doc="Moving: forward-leaning run, sword bobbing on the shoulder. Speeds up with movement speed."),
    'Air': dict(keys=AIR, ease=[None], loop=True,
                doc="Jumping or falling: knee up, free arm out for balance."),
    'Slash1': dict(keys=SLASH1, ease=SWING_EASE, additive=['RightLeg','LeftLeg'], delays=OVERLAP, fadeOut=0.22,
                   doc="M1 1: right to left horizontal slash."),
    'Slash2': dict(keys=SLASH2, ease=SWING_EASE, additive=['RightLeg','LeftLeg'], delays=OVERLAP, fadeOut=0.22,
                   doc="M1 2: backhand, left to right."),
    'Slash3': dict(keys=SLASH3, ease=SWING_EASE, additive=['RightLeg','LeftLeg'], delays=OVERLAP, fadeOut=0.22,
                   doc="M1 3: rising diagonal."),
    'Cleave': dict(keys=CLEAVE, ease=SWING_EASE, additive=['RightLeg','LeftLeg'], delays=OVERLAP, fadeOut=0.28,
                   doc="Finisher: huge horizontal cleave that wraps around the body."),
    'Rising': dict(keys=RISING, ease=SWING_EASE, additive=['RightLeg','LeftLeg'], delays=OVERLAP, fadeOut=0.28,
                   doc="Finisher (jump held): rising vertical slash."),
    'Chop': dict(keys=CHOP, ease=SWING_EASE, delays=OVERLAP, fadeOut=0.28,
                 doc="Finisher (airborne): two-handed overhead chop."),
    'Entrance': dict(keys=ENTRANCE,
                     ease=[None, LINEAR, SINE_IO, SINE_IO, QUART_OUT, LINEAR, LINEAR, LINEAR, LINEAR, LINEAR,
                           SINE_IO, QUAD_IN, SINE_OUT, SINE_IO],
                     delays={'Sword': 0.025, 'Head': -0.02},
                     events=[(0.30, 'Grimoire'), (1.0, 'Draw'), (1.70, 'Slam'), (2.25, 'Settle')],
                     fadeIn=0.08, fadeOut=0.25,
                     doc="Spawn entrance: crouched landing, grimoire appears, sword drawn from it, twirled overhead, slammed into the ground, rested on the shoulder."),
}

def num(v):
    s = ("%.3f" % v).rstrip('0').rstrip('.')
    return '0' if s in ('-0', '') else s

def value(v):
    kind, *args = v
    while kind in ('rot', 'limb') and len(args) > 1 and args[-1] == 0:
        args = args[:-1]
    return f"{kind}({', '.join(num(a) for a in args)})"

ORDER = ['Torso', 'Head', 'RightArm', 'Sword', 'LeftArm', 'RightLeg', 'LeftLeg']

def emit_pose(pose, indent):
    lines = [indent + "{"]
    for k in ORDER:
        if k in pose:
            lines.append(f"{indent}\t{k} = {value(pose[k])},")
    lines.append(indent + "}")
    return "\n".join(lines)

out = ['''--[[
	Anti-Magic Knight animation data.

	GENERATED by tools/anim/emit.py from tools/anim/asta_anims.py. Every
	keyframe and the in-betweens are checked against an R6 model of the rig
	(blade clear of the body, tip above the floor), so edit the Python and
	re-run it instead of editing this file by hand.

	Each animation: keys = { {time, pose, easingStyle?, easingDirection?}, ... }
	  rot(x, y, z)          torso/head/leg rotation (degrees)
	  limb(pitch, yaw, roll) arm/leg aim (degrees)
	  aim(x, y, z)          which way the blade points, in character space
	                        (X right, Y up, -Z forward); the wrist is solved
	                        from it when the clip is built
]]

local rad = math.rad

local function rot(x: number, y: number?, z: number?): CFrame
	return CFrame.Angles(rad(x), rad(y or 0), rad(z or 0))
end

local function limb(pitch: number, yaw: number?, roll: number?): CFrame
	return CFrame.Angles(0, rad(yaw or 0), 0) * CFrame.Angles(0, 0, rad(roll or 0)) * CFrame.Angles(rad(pitch), 0, 0)
end

local function aim(x: number, y: number, z: number): { aim: Vector3 }
	return { aim = Vector3.new(x, y, z) }
end

local Animations = {}
''']

for name, spec in SPEC.items():
    out.append(f"-- {spec['doc']}")
    out.append(f"Animations.{name} = {{")
    if spec.get('loop'): out.append("\tloop = true,")
    if 'fadeIn' in spec: out.append(f"\tfadeIn = {num(spec['fadeIn'])},")
    if 'fadeOut' in spec: out.append(f"\tfadeOut = {num(spec['fadeOut'])},")
    if spec.get('additive'):
        out.append("\tadditive = { " + ", ".join(f"{k} = true" for k in spec['additive']) + " },")
    if spec.get('delays'):
        out.append("\tdelays = { " + ", ".join(f"{k} = {num(v)}" for k, v in spec['delays'].items()) + " },")
    if spec.get('events'):
        out.append("\tevents = {")
        for t, e in spec['events']:
            out.append(f'\t\t{{ time = {num(t)}, name = "{e}" }},')
        out.append("\t},")
    out.append("\tkeys = {")
    for (t, pose), ease in zip(spec['keys'], spec['ease']):
        out.append("\t\t{")
        out.append(f"\t\t\t{num(t)},")
        out.append(emit_pose(pose, "\t\t\t") + ",")
        if ease:
            out.append(f'\t\t\t"{ease[0]}",')
            out.append(f'\t\t\t"{ease[1]}",')
        out.append("\t\t},")
    out.append("\t},")
    out.append("}\n")

out.append("return Animations\n")
import sys
open(sys.argv[1], 'w').write("\n".join(out))
print("wrote", sys.argv[1])
